In [9]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [10]:
df=pd.read_csv("data/Student_Marks.csv")
df.head()

   number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811
3               6       7.909  53.018
4               8       7.811  55.299

In [11]:
df.columns=['sinif','saat','puan']

df.head()

   sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811
3      6  7.909  53.018
4      8  7.811  55.299

In [12]:
y=df[['puan']]
x=df[['sinif','saat']]

In [13]:
lm=LinearRegression()
model=lm.fit(x,y)

In [14]:
#y=ax+b

model.coef_ #katsayi

array([[1.86405074, 5.39917879]])

In [15]:
model.intercept_ #sabit

array([-7.45634623])

In [16]:
model.predict([[4,5]])

c:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[26.99575068]])

In [18]:
(4*1.86405074)+ (5*5.39917879)+(-7.45634623)

26.99575068

In [19]:
df.head()

   sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811
3      6  7.909  53.018
4      8  7.811  55.299

In [24]:
s1=model.predict([[3,4.508]])[0][0]
s1

c:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

22.47530397094242

In [22]:
(19.202-s1)/19.202

array([-0.17046682])

In [23]:
model.score(x,y)

0.9403656320238896