In [75]:
# MSE RMSE MAE MAPE

In [76]:
import pandas as pd 
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.metrics import mean_squared_error,mean_absolute_error,mean_absolute_percentage_error

In [77]:
df=pd.read_csv("data/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [78]:
df=pd.get_dummies(df,columns=['sex','smoker','region'],drop_first=True, dtype=int)
df.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,0,1,0,0,1
1,18,33.770,1,1725.55230,1,0,0,1,0
2,28,33.000,3,4449.46200,1,0,0,1,0
3,33,22.705,0,21984.47061,1,0,1,0,0
4,32,28.880,0,3866.85520,1,0,1,0,0

In [79]:
y=df['charges']
x=df.drop('charges',axis=1)

In [80]:
lm=LinearRegression()
model=lm.fit(x,y)
model.score(x,y)

0.7509130345985207

In [81]:
model.predict([[19,26,0,1,1,0,0,1]])

c:\Users\hp\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([24517.93110714])

In [82]:
df_hata=pd.DataFrame()

In [83]:
df_hata['y']=y
df_hata

                y
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [84]:
y_tahmin=model.predict(x)
df_hata['tahmin']=y_tahmin

df_hata

                y        tahmin
0     16884.92400  25293.713028
1      1725.55230   3448.602834
2      4449.46200   6706.988491
3     21984.47061   3754.830163
4      3866.85520   5592.493386
...           ...           ...
1333  10600.54830  12351.323686
1334   2205.98080   3511.930809
1335   1629.83350   4149.132486
1336   2007.94500   1246.584939
1337  29141.36030  37085.623268

[1338 rows x 2 columns]

In [85]:
df_hata['error']=y-y_tahmin
df_hata.head()

             y        tahmin         error
0  16884.92400  25293.713028  -8408.789028
1   1725.55230   3448.602834  -1723.050534
2   4449.46200   6706.988491  -2257.526491
3  21984.47061   3754.830163  18229.640447
4   3866.85520   5592.493386  -1725.638186

In [86]:
#MSE = hataların karesinin ortalaması
#MAE: Hataların mutlak ortalaması
#RMSE: MSE'nin kareköküdür
#MAPE: Hatanın yüzdesidir

In [87]:
df_hata['squared_error']=df_hata['error']**2

In [88]:
df_hata['abs_error']=np.abs(df_hata['error'])

In [89]:
df_hata['percent_error']=np.abs(y-y_tahmin)/y

In [90]:
df_hata.head()

,y,tahmin,error,squared_error,abs_error,percent_error
0,16884.92400,25293.713028,-8408.789028,7.070773e+07,8408.789028,0.498006
1,1725.55230,3448.602834,-1723.050534,2.968903e+06,1723.050534,0.998550
2,4449.46200,6706.988491,-2257.526491,5.096426e+06,2257.526491,0.507371
3,21984.47061,3754.830163,18229.640447,3.323198e+08,18229.640447,0.829205
4,3866.85520,5592.493386,-1725.638186,2.977827e+06,1725.638186,0.446264

In [91]:
df_hata.mean()

y                1.327042e+04
tahmin           1.327042e+04
error            6.471143e-13
squared_error    3.650189e+07
abs_error        4.170887e+03
percent_error    4.203527e-01
dtype: float64

In [92]:
mean_squared_error(y,y_tahmin)

36501893.00741544

In [93]:
mean_absolute_error(y,y_tahmin)

4170.8868941635865

In [94]:
mean_absolute_percentage_error(y,y_tahmin)

0.42035268473727033